language: php

php:
  - 5.5

services: mysql

env:
  - DB=mysql

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS restapi_test;" -uroot; fi

script: phpunit --configuration phpunit.xml --coverage-text